Km to miles
virejdasani/DiscordBots pull request #3
Opened 2022-10-04 10:00 UTC by badonyt

# Km to miles
This is a bot for Km To Miles using python.

**Example:**
![image](https://user-images.githubusercontent.com/78484256/193791658-561666ec-08ce-40cf-8da1-54dd42637ea9.png)

2022-10-04 14:29 UTC, UFifty50 commented on kmtomiles/main.py
> +CONST_prefix = '!'
`CONST_prefix` appears to be labelled as a constant, so it should be just `PREFIX` in accordance with [PEP-8](https://peps.python.org/pep-0008/#constants)

2022-10-04 14:30 UTC, UFifty50 commented on kmtomiles/main.py
> +CONST_prefix = '!'
`bot_TOKEN` appears to be constant too, and so should also be `BOT_TOKEN`

2022-10-04 14:34 UTC, virejdasani commented
Are you sure you have to do pip install discord.py? I'm pretty sure it's only discord

2022-10-04 15:04 UTC, UFifty50 requested changes
I have completed a review of this pull request, please inform me if any of my comments are wrong.

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/main.py
> +	await ctx.send(round(0.62137119*float(arg)/1.00, 5))
Using magic numbers here and at line 18 makes the code difficult to read, so it would be much better to extract them as constants to the top of the file. It would also be more accurate to use the same number of decimal places for each one. Here I've used six, but it's up to you. 
E.g. `MTOKM = 1.609346` and `KMTOM = 0.621371`
Then reference them from your methods, e.g. `round(MTOKM/arg, 6)` (again, the same number of decimal places for accuracy)

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/main.py
> +CONST_prefix = '!'
`CONST_prefix` appears to be labelled as a constant, so it should be just `PREFIX` in accordance with [PEP-8](https://peps.python.org/pep-0008/#constants)

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/main.py
> +CONST_prefix = '!'
`bot_TOKEN` appears to be constant too, and so should also be `BOT_TOKEN`

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/main.py
> +	await ctx.send(round(0.62137119*float(arg)/1.00, 5))
The `/1.00` here does nothing, I recommend removing it for readability.

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/main.py
> +	await ctx.send(round(1.60934*float(arg)/0.9999975145, 5))
Please correct me if I am wrong, but I believe that the `/0.9999975145` does nothing but add a level of inaccuracy to large conversions.

2022-10-04 15:04 UTC, UFifty50 commented on kmtomiles/README.md
> +To run this bot you have to have python 3.10<br>
To make this paragraph more concise and readable, I recommend adding each point to a list, like so: 
To run this bot you require [python 3.10](https://www.python.org/downloads/) (or higher), the discord.py pip package, and a [discord developer bot token](https://discord.com/developers/applications)

2022-10-04 15:24 UTC, badonyt commented
@virejdasani its https://pypi.org/project/discord.py/

2022-10-04 15:24 UTC, badonyt commented on kmtomiles/README.md
> +To run this bot you have to have python 3.10<br>
Make a pull request

2022-10-04 15:26 UTC, badonyt commented on kmtomiles/main.py
> +	await ctx.send(round(1.60934*float(arg)/0.9999975145, 5))
Google told me it was like that
Example(with 132):
https://www.google.com/search?client=firefox-b-d&q=1.60934*132%2F0.9999975145
Googles response: 
https://www.google.com/search?client=firefox-b-d&q=miles+to+km

2022-10-04 15:26 UTC, badonyt commented on kmtomiles/main.py
> +	await ctx.send(round(0.62137119*float(arg)/1.00, 5))
Make pull request

2022-10-04 15:26 UTC, edris6 commented on kmtomiles/main.py
> +CONST_prefix = '!'
Make pull request

2022-10-04 15:27 UTC, badonyt commented on kmtomiles/main.py
> +	await ctx.send(round(0.62137119*float(arg)/1.00, 5))
Make pull request

2022-10-04 15:28 UTC, badonyt commented
Also thanks @UFifty50 for the suggestions please make a pull request from what i told into my fork. Please.

Thanks,

2022-10-10 11:15 UTC, virejdasani commented
Looks good, thanks!

2022-10-10 11:15 UTC, merged